install:
  - cmd: SET PATH=%M2_HOME%\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET LIBJAGGED_CMAKE_FLAGS=-DUSE_SDL=OFF
  - cmd: SET LIBJAGGED_TEST_CMAKE_FLAGS=-DUSE_SDL=OFF
build_script:
  - git submodule init
  - git submodule update
  - make.cmd
  - make.cmd install
  - mvn clean package --batch-mode -DskipTest
test_script:
  - mvn clean install --batch-mode
cache:
  - C:\Users\appveyor\.m2
branches:
  only:
    - master
artifacts:
  - path: '**\*'
    name: MyApp
